const AllJournals = [
  {
    name: "HEAD IN THE CLOUDS",
    image: 'clouds',
    imgDes: "A piece of art I created that shows a man's head surrounded by clouds.",
    projDate: "27 July, 2021",
    shortDes: "An ode to creative endeavors.",
    description1: "As someone who often finds themself tangled in an endless array of personal projects, I often feel as if new ideas and goals are practically dripping from my ears at times. I've found that as I scribble items off of my to-do list an equal amount seem to simultaneously appear at the bottom. Being a programmer, a visual artist, a film photographer, a musician, and an avid fan of travel, I usually have at least one more thing or idea 'coming down the pipe'. I've spent many years of my life in a chonic state of 'damage control' as the frenzy that is young-adulthood seems to teem around me. How does one create work/life balance if the two seem to be always bleeding over each other? How can I categorize and separate both a time to work, and a time for creative flow? Both are equally significant, and one without the other disrupts the delicate balance that is 'contentness' that sits perched in the forefront of our brains. The answer? Admittedly, I don't know.",
    description2: "I'm two weeks away from my anticipated graduation from a ten-month coding bootcamp now, and as I look back at all the projects I've done, I see among them the dead and forgotten never-to-be's of the seemingly brilliant ideas my peers and I once had. After taking a second to mourn the losses of all our discarded apps, I begun to see parallels between a job I had spent the first couple decades of my life detesting, and something that I hold very dear to my heart: the creative process. The last year of life has been wildly formative for me. I now understand why the coined word for my program is 'bootcamp'. The first day of class, I remember sitting down and preparing to learn a couple new things about web development over the coming months. Instead what I received was an entire warzone of information overload. I quickly realized that programming wasn't for the faint of heart, and seriously reconsidered my decision for months after. With new information every two weeks paired with alternating personal code reviews, I genuinely didn't think I would make it past month numero uno. I networked with a few coding bootcamp graduates to see how on earth they managed. The resounding response was, as Johnny Cash so well put it, 'one piece at a time'. Abiding by this advice, I decided I was going to do just that. I was just going to try one day at a time. Days turned into weeks, and weeks turned into months. Soon enough, I caught myself audibly laughing at some of the code I had proudly written just months earlier. It was at that point that my instructor informed me 'you did it!'. I wasn't entirely sure what she meant until she explained:",
    quote: `'Learning how to program doesn't mean learning how to write code. It means learning how to learn.'`,
    description3: "Her statement stuck with me then, and continues to. The more I think about it, the more it makes sense. It's impossible for even the best Senior Software Engineer to know everything there is to know about every language, every solution to manipulating linked lists, or how on earth one goes about solving the Pancake Sorting problem. One could spend an entire lifetime doing nothing but eating, sleeping, and breathing code (believe me, I know what that's like) and still wake up the next morning with new things to learn. Some may find that defeating, I find it exciting. I've spent so long with my head in the clouds, constantly anticipating crossing the next project off my to-do list while it recursively increases in length. I thought that reaching the end of that list would mean contentness. Because 'crossing that last item off is going to be so great!'. However, isn't life about simply being here while we have it? About the process of learning and failing over and over again until we get it right? Chasing the end of a scrap of paper seems like a dreary way to exist. I've learned even moreso over the last year that I am capable of anything I put my mind to, and you are too. I find excitement in refactoring; In adding an entirely new to-do list to the end of the first. There's so much to learn, and so much to create.",
    closer: "I've managed to drink from the firehose of information for the last year. I've decided I love it.",
    id: 115
  },
  {
    name: "THE HIGH ONE",
    image: 'alaska',
    imgDes: "A photo taken from a biplane in my travels to Alaska.",
    projDate: "10 July, 2021",
    shortDes: "A brief look into my travels in Alaska.",
    description1: "In summer of 2019, I got the opportunity to work a seasonal position at a small cabin complex in Denali National park. During my short few months of time there, I was fortunate enough to see a handful of sites most people only dream about. It was there in that small corner of the earth that a piece of my heart remains forever captured by the landscape.",
    description2: "Being my first chance to spend an extended amount of time away from home, I left with a duffle bag full of clothes and a chest filled with anticipation. I had decided a few months prior that instead of flying straight to Fairbanks out of Portland, that I'd be missing too much of what was to be seen lazily dozing away in an airplane cabin. Instead, I opted to make the 5,000 mile round-trip drive, passing through Canada along the way -- one of my best decisions to date. The days were long, and the miles longer. Much of the time I drove through winding Canadian 'freeways' (many of which were made up of haphazardly poured gravel) with patchy cell service, and gas stations scattered hundreds of miles apart. Through these patches, often times my only company was the rumbling of the pavement beneath me and the patter of rain against the windshield. I wouldn't trade those vacant stretches of near silence for anything. Along the way I had the fortune to meet dozens of kind individuals, a few black bears, three foxes, and even one lonely lynx. As gas prices climbed, so did my anticipation of arrival. 8 long days later, I arrived onsite and began my summer.",
    quote: `'You should never go to Alaska as a young man because you'll never be satisfied with any other place as long as you live.' - John Muir`,
    description3: "What followed was an unforgettable few months of surreal hiking sites, new friends, 11 pm campfires beneath a fully-lit sky, and more mosquito bites than I've had in the rest of my life combined. Down the dirt road from where I was housed, I met a local private pilot named Bob. After a few hours of relaxed campfire disussion, Bob offered me and my buddy Fitz a personal ride in his biplane around the Denali summit the next day in exchange for a free meal at the cabin's restaurant. We accepted, of course. The scale of my surroundings on that plane ride is something I still fail to be able to wrap my head around today. I've seen my fair share of mountains before, but this was unlike anything I had ever seen. Our loud, rattling, 40-year-old plane quickly became but a speck of suspended dust in the gleaming majesty that is 'The High One', as the native american locals called it.",
    closer: "Since then, I do my best to make it back to Alaska during the summer for a few days at a time. I find the solitude of disconnecting and retreating to the mountains brings with it catharsis, a sense of grounding, and an important perspective check to remind us of our humanness, and all the wonders that it to offer.",
    id: 125
  },
  {
    name: "DAKROOM PHOTOGRAPHY",
    image: 'darkroom',
    imgDes: "An image of a woman working in a film darkroom.",
    projDate: "11 April 2021",
    shortDes: "Quis autem vel eum iure reprehenderit qui in ea voluptate.",
    description: "This is an entry regarding my photography hobby. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    id: 135
  }
];

export default AllJournals;